apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-consumer-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-consumer-microservice
  template:
    metadata:
      labels:
        app: camel-consumer-microservice
    spec:
      containers:
        - name: camel-consumer-microservice
          image: sachetwasti61/camel-consumer-microservice
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 8182
---
apiVersion: v1
kind: Service
metadata:
  name: camel-consumer-microservice-srv
spec:
  selector:
    app: camel-consumer-microservice
  ports:
    - port: 8182
      targetPort: 8182